### ISSUE TITLE
Evaluate Minio

### ISSUE THREAD

**Issue by ctengel** [ctengel/objectindex#5]
- [x] Fix the Go install issue
  - https://docs.min.io/docs/minio-quickstart-guide.html
  - https://maelvls.dev/go111module-everywhere/
  - https://stackoverflow.com/questions/24878737/what-is-the-difference-between-go-get-and-go-install
- [x] Look at the on disk format
- [x] Last chance for competition
  - https://hypercore-protocol.org/
  - https://zenko.readthedocs.io/en/latest/operation/Architecture/index.html
  - https://s3-server.readthedocs.io/en/latest/ARCHITECTURE.html
  - https://zenko.readthedocs.io/en/latest/

**Comment by ctengel** [comment]
Opened issue - https://github.com/minio/minio/issues/15001

**Comment by ctengel** [comment]
Openio? Openmediavault? Owncloud?

**Comment by ctengel** [comment]
Client - [boto3](https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html) ([more](https://boto3.amazonaws.com/v1/documentation/api/1.9.46/guide/s3-example-creating-buckets.html)) or [minio-py](https://docs.min.io/docs/python-client-quickstart-guide.html)

**Comment by ctengel** [comment]
Going to use boto3 - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#service-resource

**Comment by TjieLee** [comment]
Is there a better solution that can use go install now? Thanks.

**Comment by ctengel** [comment]
Note since then we hit another major minio issue with auto upgrading and losing backward compatibility

In happy news lots of benefits from the new version hopefully

**Comment by ctengel** [comment]
1. Free up laptop space
2. Reattempt go install
3. Reread docs in #8 about setting up buckets
4. Attempt to setup
5. Document in README
6. Close this issue and move on to #11

**Comment by ctengel** [comment]
- https://www.linkedin.com/pulse/build-your-own-private-cloud-home-raspberry-pi-minio-huerta-arias
- https://min.io/docs/minio/linux/index.html?ref=docs-redirect
- https://min.io/docs/minio/linux/administration/identity-access-management.html?ref=docs-redirect
- https://stackoverflow.com/questions/42616518/minio-hows-bucket-policy-related-to-anonymous-authorized-access

**Comment by ctengel** [comment]
From https://www.linkedin.com/pulse/build-your-own-private-cloud-home-raspberry-pi-minio-huerta-arias

```
$ cat /boot/config.txt
# Increase power available to USB ports
max_usb_current=1
```

Sharable URLs

```
$ systemctl list-units | grep '/home/pi/data' | awk '{ print $1 }'
home-pi-data.mount
$ cat  /etc/systemd/system/minio.service
[Unit]
Description=Minio Storage Service
After=network-online.target home-pi-data.mount
[Service]
ExecStart=/home/pi/start.sh
WorkingDirectory=/home/pi
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
$ sudo systemctl start minio
$ sudo systemctl status minio
$ sudo systemctl enable minio
```

**Comment by ctengel** [comment]
From https://min.io/docs/minio/linux/index.html?ref=docs-redirect 
- https://min.io/docs/minio/linux/administration/identity-access-management.html#minio-authentication-and-identity-management
  - also included above
- https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html#deploy-minio-distributed

https://stackoverflow.com/questions/42616518/minio-hows-bucket-policy-related-to-anonymous-authorized-access

**Comment by ctengel** [comment]
Consider Fedora, now supported officially on Raspbery Pi 4 as of Fedora 37

**Comment by ctengel** [comment]
this is the infra piece - let's execute on https://github.com/ctengel/objectindex/issues/5#issuecomment-1305550223

**Comment by ctengel** [comment]
https://github.com/minio/console

**Comment by ctengel** [comment]
trying to figure out still - 
- how to handle user access to bucket
  - https://blog.nikhilbhardwaj.in/2020/02/25/minio-bucket-policy/
  - https://github.com/minio/minio/issues/9530
  - https://min.io/docs/minio/linux/administration/identity-access-management/policy-based-access-control.html
  - https://stackoverflow.com/questions/74603734/how-to-restrict-access-by-particular-user-to-bucket-using-bucket-level-policy-in
- anonymous bucket access https://stackoverflow.com/questions/42616518/minio-hows-bucket-policy-related-to-anonymous-authorized-access
- do we need `MINIO_DISK_USAGE_CRAWL`???
- do we need https://github.com/minio/console
- final rpi setup
  - usb power
  - systemd

figure out and document above, then close this issue

fedora question can stick with #2

**Comment by ctengel** [comment]
I believe access is solved, need to add example JSON and commands to README

**Comment by ctengel** [comment]
After doing and splitting some stuff off, the only thing left to do is to get minio running on rpi, including usb power fix and systemd

**Comment by ctengel** [comment]
Others:

- https://github.com/juicedata/juicefs
- https://github.com/moosefs/moosefs
- https://filiphanes.sk/en/dont-reinvent-file-object-storage-api/

**Comment by ctengel** [comment]
testing now for streaming

**Comment by ctengel** [comment]
mp4 streaming seems to work (actual mp4 and not mp2t disguised as mp4) fantastically - firefox requests appropriate sections and minio sends them - test success!

**Comment by ctengel** [comment]
More stability/maturity issues - 

`mc: <ERROR> Deprecated command. Please use 'mc admin policy create' instead.`

upon calling `MinioAdmin.policy_add()` which seems to run `mc admin policy add`

Essentially the CLI deprecated a usage to the point of breaking it without even letting the official minio python wrapper/library catch up...

**Comment by ctengel** [comment]
See minio/minio-py#1293

**Comment by ctengel** [comment]
Seems fixed in latest, with `pip3 install https://github.com/minio/minio-py/archive/refs/heads/master.zip`

**Comment by ctengel** [comment]
At this point  minio-py seems fixed as of [7.1.16](https://github.com/minio/minio-py/releases/tag/7.1.16)

Remaining

- [ ] formal test of 7.1.16
- [ ] systemd
     - see https://github.com/ctengel/objectindex/issues/5#issuecomment-1306005591 - document this
     - perhaps docker?
- [ ] power fixes
     - see https://github.com/ctengel/objectindex/issues/5#issuecomment-1306005591 - document this
     - do we need a hub? monitor dmesg

**Comment by ctengel** [comment]
`dmesg` is clean and so is minio log for over a week - that is good

Just need to determine if any power tweaks (software/firmware or hardware (usb hub etc)) are needed...

**Comment by ctengel** [comment]
It appears max usb current no longer needs to be tweaked https://www.raspberrypi.com/documentation/computers/config_txt.html#max_usb_current

One less thing for us to do however bad news in that it seems any power woes have to be fixed in hardware

**Comment by ctengel** [comment]
Will monitor and open separate HW issue as needed. Minio is it for now!
